# CI/CD Workflow
name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout repository
    - uses: actions/checkout@v2

    # Setup node.js 
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Setup PHP
    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2

    # Install SSH key to VM
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known-hosts: ${{ secrets.KNOWN_HOSTS }}

    # Cache
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Resolve Dependencies
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
        composer update --prefer-dist --no-progress --no-suggest

    # Build assets
    - name: Build assets
      run: |
        yarn install
        yarn encore prod
    
    # Compress repository
    - name: Compress repository contents
      run: |
        cd ../
        tar -czf SymfonyEx.tgz SymfonyEx/

    # Deploy
    - name: Deploy using SFTP
      run: |
        cd ../
        ssh r-techlab@r-techlab.sakura.ne.jp "cd symfony;ls"
        ssh r-techlab@r-techlab.sakura.ne.jp "ls"
        ssh-keyscan -H r-techlab.sakura.ne.jp >> ~/.ssh/known_hosts
        ssh r-techlab@r-techlab.sakura.ne.jp "ls"
        ssh r-techlab@r-techlab.sakura.ne.jp "ls www/Enchan"
        ssh r-techlab@r-techlab.sakura.ne.jp "pwd"
        echo "Is it iiiiiiiiiiiinfinityyyyyyyyyyyyyy loooooooooooop!!?!??!?!!?!??!?!!!??!!??!?!?!?!?!!?!?"


